import requests
from bs4 import BeautifulSoup
import datetime

def fetch_news():
    # --- IDENTITY ---
    AUTHOR_NAME = "NISHANTH"
    PROJECT_NAME = "AI & TECH NEWS REPORTER"
    
    url = "https://www.bbc.com/technology"
    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.content, 'html.parser')
        headlines = soup.find_all(['h2', 'h3'], limit=15)

        # Current Time for the website
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # --- HTML DESIGN START ---
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{PROJECT_NAME}</title>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background-color: #f0f2f5; color: #333; }}
                .card {{ max-width: 800px; margin: auto; background: white; padding: 30px; border-radius: 15px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
                h1 {{ color: #1a73e8; text-align: center; border-bottom: 3px solid #1a73e8; padding-bottom: 10px; }}
                .author-info {{ text-align: center; background: #e8f0fe; padding: 10px; border-radius: 8px; margin-bottom: 20px; }}
                .news-box {{ border-left: 5px solid #1a73e8; margin-bottom: 15px; padding: 15px; background: #fafafa; transition: 0.3s; }}
                .news-box:hover {{ background: #f1f1f1; transform: scale(1.01); }}
                .news-box h3 {{ margin: 0 0 10px 0; color: #202124; }}
                a {{ text-decoration: none; color: #1a73e8; font-weight: bold; font-size: 0.9em; }}
                .footer {{ text-align: center; margin-top: 30px; font-size: 0.8em; color: #70757a; }}
            </style>
        </head>
        <body>
            <div class="card">
                <h1>🤖 Latest AI & Tech News</h1>
                <div class="author-info">
                    <p><strong>Developed by:</strong> {AUTHOR_NAME} (2nd Year AI & DS)</p>
                    <p><strong>Last Updated:</strong> {now}</p>
                </div>
        """

        count = 0
        for news in headlines:
            title = news.get_text().strip()
            parent_a = news.find_parent('a') or news.find('a')
            
            if parent_a and len(title) > 25:
                count += 1
                link = parent_a['href']
                if not link.startswith('http'): link = "https://www.bbc.com" + link
                
                # Adding news items to HTML
                html_content += f"""
                <div class="news-box">
                    <h3>{count}. {title}</h3>
                    <a href="{link}" target="_blank">Read Full Article &rarr;</a>
                </div>
                """
            if count == 5: break

        html_content += f"""
                <div class="footer">
                    &copy; 2026 {AUTHOR_NAME} | Automated via GitHub Actions
                </div>
            </div>
        </body>
        </html>
        """
        # --- HTML DESIGN END ---

        # 1. Print to Logs (as usual)
        print(f"Report Generated by {AUTHOR_NAME}")
        
        # 2. Save as index.html (This makes the link work!)
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        
        print("✅ index.html has been updated successfully!")

    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    fetch_news()
                
