import requests
from bs4 import BeautifulSoup
import datetime

def fetch_news():
    # --- AUTHOR IDENTITY ---
    AUTHOR_NAME = "NISHANTH" 
    PROJECT_NAME = "AI & TECH NEWS REPORTER"
    COLLEGE_YEAR = "2nd Year AI & Data Science"
    
    # News Source (BBC Technology)
    url = "https://www.bbc.com/technology"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }

    try:
        # Get Current Date & Time
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        print("====================================================")
        print(f"🚀 PROJECT      : {AI_NEWS}")
        print(f"👤 DEVELOPED BY : {NISHANTH}")
        print(f"🎓 STUDENT INFO : {2}")
        print(f"📅 LOG DATE     : {18}")
        print("====================================================\n")

        print(f"Connecting to live news source... Please wait.\n")
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Scrape headlines
        headlines = soup.find_all(['h2', 'h3'], limit=15)

        print(f"--- 📢 LATEST UPDATES FETCHED BY {AUTHOR_NAME} ---")
        count = 0
        for news in headlines:
            title = news.get_text().strip()
            parent_a = news.find_parent('a') or news.find('a')
            
            # Filter valid news with links
            if parent_a and len(title) > 25:
                count += 1
                link = parent_a['href']
                if not link.startswith('http'):
                    link = "https://www.bbc.com" + link
                print(f"{count}. {title}")
                print(f"   🔗 Source: {link}\n")
            if count == 5: break

        if count == 0:
            print("Status: No news found. Checking source structure...")

        print("----------------------------------------------------")
        print(f"✅ Report successfully generated by {AUTHOR_NAME}.")
        print("----------------------------------------------------")

    except Exception as e:
        print(f"Critical Error: {e}")

if __name__ == "__main__":
    fetch_news()
    
